cache:
        paths:
                - venv/

compile:
        stage: build
        script:
                - python3 -m venv venv
                - . venv/bin/activate
                - pip install -r requirements.txt

test:
        stage: test
        script:
                - . venv/bin/activate
                - pytest

deploy:
        stage: deploy
        script:
                - . venv/bin/activate
                - flask run --host=146.169.42.69 >> log.txt 2>61 &

herokudeploy:
        stage: deploy
        script:
                - dpl --provider=heroku --app=footml-fpl --api-key=71fa67c5-a907-4c53-90a4-be940b68fb3d
